### ISSUE TITLE
[pytket-qiskit] backend_info to_dict() error for AerBackend with NoiseModel

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-extensions#264]
Error in the `backend.backend_info.to_dict()` for the AerBackend with the qiskit noismodel.

```from pytket.extensions.qiskit import AerBackend
import qiskit.providers.aer.noise as noise

error_2 = noise.depolarizing_error(0.1, 2)
noise_model = noise.NoiseModel()
noise_model.add_quantum_error(error_2, ['cx'], [0,1])
backend = AerBackend(noise_model)
backend.backend_info.to_dict()```

Is generating an error in the last function call:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/site-packages/pytket/backends/backendinfo.py", line 131, in to_dict
    self_dict = asdict(self)
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1073, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1080, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1110, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1111, in <genexpr>
    _asdict_inner(v, dict_factory))
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1110, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1111, in <genexpr>
    _asdict_inner(v, dict_factory))
  File "/home/cq/anaconda3/envs/tket-bug/lib/python3.8/dataclasses.py", line 1110, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None

**Comment by cqc-melf** [comment]
Solved
