### ISSUE TITLE
Error converting compiled circuit with conditional gate on second register

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-extensions#275]
With `circ.qasm`:
```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[2];
creg m[1];
measure q[1] -> m[0];
if(m==1) x q[1];
h q[0];
cx q[0],q[1];
measure q[1] -> c[1];
h q[0];
measure q[0] -> c[0];
```

The following code generates an error:
```python
from pytket.extensions.qiskit import tk_to_qiskit, AerBackend
from pytket.qasm import circuit_from_qasm

backend = AerBackend()

c0 = circuit_from_qasm("circ.qasm")
print(c0.get_commands())
qc0 = tk_to_qiskit(c0)
print(qc0)
c = backend.get_compiled_circuit(c0, optimisation_level=1)
print(c.get_commands())
qc = tk_to_qiskit(c)
print(qc)
```

Output:
```
[Measure q[1] --> m[0];, H q[0];, IF ([m[0]] == 1) THEN X q[1];, CX q[0], q[1];, Measure q[1] --> c[1];, H q[0];, Measure q[0] --> c[0];]
     ┌───┐            ┌───┐┌─┐
q_0: ┤ H ├─────────■──┤ H ├┤M├
     └┬─┬┘ ┌───┐ ┌─┴─┐└┬─┬┘└╥┘
q_1: ─┤M├──┤ X ├─┤ X ├─┤M├──╫─
      └╥┘  └─╥─┘ └───┘ └╥┘  ║ 
c: 2/══╬═════╬══════════╩═══╩═
       ║     ║          1   0 
       ║  ┌──╨──┐             
m: 1/══╩══╡ 0x1 ╞═════════════
       0  └─────┘             
[Measure q[1] --> m[0];, TK1(0.5, 0.5, 0.5) q[0];, IF ([m[0]] == 1) THEN X q[1];, CX q[0], q[1];, Measure q[1] --> c[1];, TK1(0.5, 0.5, 0.5) q[0];, Measure q[0] --> c[0];]
Traceback (most recent call last):
  File "/home/alec/tmp/ikbug/qcbug.py", line 12, in <module>
    qc = tk_to_qiskit(c)
  File "/home/alec/r/pytket-extensions/modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py", line 568, in tk_to_qiskit
    append_tk_command_to_qiskit(
  File "/home/alec/r/pytket-extensions/modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py", line 515, in append_tk_command_to_qiskit
    return qcirc.to_instruction()
  File "/home/alec/r/pytket-extensions/env-pytket-extensions-3.9/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1482, in to_instruction
    return circuit_to_instruction(self, parameter_map, label=label)
  File "/home/alec/r/pytket-extensions/env-pytket-extensions-3.9/lib/python3.9/site-packages/qiskit/converters/circuit_to_instruction.py", line 127, in circuit_to_instruction
    raise QiskitError(
qiskit.exceptions.QiskitError: 'Cannot convert condition in circuit with multiple classical registers to instruction'
```

This is rather puzzling: the original circuit (which was successfully converted) differs from the compiled circuit only in that H gates have been replaced by TK1 gates. If we change the optimization level to 0, the circuits appear identical and there is no error.

**Comment by irfankhan10** [comment]
@cqc-alec Error seems to be coming from SynthesizeTKET
